DA: false
autocast: true
batchsize: 8
block: 3
color_jitter: false
data_dir: C:\Users\Jack_\Desktop\newTestDataset\train
erasing_p: 0
fp16: false
gpu_ids: '0'
h: 256
kl_loss: false
lr: 0.01
moving_avg: 1.0
name: FSRA
nclasses: 701
num_epochs: 10
num_worker: 4
pad: 0
sample_num: 1.0
share: true
steps:
- 70
- 110
train_all: false
triplet_loss: 0.3
use_gpu: true
views: 2
w: 256
warm_epoch: 0
